-- Create a table for storing leads
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  whatsapp text not null,
  email text not null
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;

-- Create a policy to allow anyone to insert leads (public form)
create policy "Enable insert for everyone" on public.leads
  for insert
  with check (true);

-- Create a policy to allow only authenticated users (admins) to view leads
-- Note: You need to be logged in to the Supabase dashboard to view data by default, 
-- but this policy ensures API security if you build an admin panel later.
create policy "Enable read access for authenticated users only" on public.leads
  for select
  using (auth.role() = 'authenticated');
